djangoProject/boss/urls.py
from django.urls import path
from boss import views

urlpatterns = [
    path('timeinput/', views.time_input, name='timeinput'),
    path('orders/<int:shop>', views.order_list, name='order_list')
]

djangoProject/delivery/urls.py
from django.urls import path
from delivery import views

app_name = 'delivery'

urlpatterns = [
    path('orders/', views.order_list, name='order_list')
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('order/', include('order.urls')),
    path('boss/', include('boss.urls')),
    path('delivery/', include('delivery.urls')),
    path('user/', include('user.urls'))
]

djangoProject/order/urls.py
from django.urls import path
from order import views

urlpatterns = [
    path('shops/', views.shop, name='shop'),
    path('menus/<int:shop>', views.menu, name='menus'),
    path('order/', views.order, name='order')
]

djangoProject/user/urls.py
from django.urls import path
from user import views

urlpatterns = [
    path('user/', views.user, name='user'),
    path('login/', views.login, name='login')
]

djangoProject/order/models.py
from django.db import models


class Shop(models.Model):
    shop_name = models.CharField(max_length=20)
    shop_address = models.CharField(max_length=40)


class Menu(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    food_name = models.CharField(max_length=20)


class Order(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    order_date = models.DateTimeField('date ordered')
    address = models.CharField(max_length=40)
    estimated_time = models.IntegerField(default=-1)
    deliver_finished = models.BooleanField(default=0)


class Orderfood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food_name = models.CharField(max_length=20)

djangoProject/user/models.py
from django.db import models


class User(models.Model):
    user_name = models.CharField(max_length=20)
    user_type = models.IntegerField()   # 0 user 1 사장 2 배달기사

djangoProject/boss/views.py
from order.models import Order
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render


@csrf_exempt
def time_input(request):
    if request.method == 'POST':
        order_item = Order.objects.get(pk=int(request.POST['order_id']))
        shop = order_item.shop.id
        order_item.estimated_time = int(request.POST['estimated_time'])
        order_item.save()
        return render(request, 'boss/success.html', {'shop': int(shop)})
    else:
        return HttpResponse(status=404)


@csrf_exempt
def order_list(request, shop):
    if request.method == 'GET':
        order_list = Order.objects.filter(shop=shop)
        return render(request, 'boss/order_list.html', {'order_list': order_list})
    else:
        return HttpResponse(status=404)

djangoProject/delivery/views.py
from django.shortcuts import render
from order.models import Order
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def order_list(request):
    if request.method == 'GET':
        order_list = Order.objects.all()
        return render(request, 'delivery/order_list.html', {'order_list': order_list})

    elif request.method == 'POST':
        order_item = Order.objects.get(pk=int(request.POST['order_id']))
        order_item.deliver_finished = 1
        order_item.save()
        return render(request, 'delivery/success.html')

djangoProject/order/views.py
from django.shortcuts import render
from order.models import Shop, Menu, Order, Orderfood
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from order.serializers import ShopSerializer, MenuSerializer
from django.utils import timezone


@csrf_exempt
def shop(request):
    if request.method == 'GET':
        shop = Shop.objects.all()
        # serializer = ShopSerializer(shop, many=True)
        # return JsonResponse(serializer.data, safe=False)
        return render(request, 'order/shoplist.html', {'shop_list': shop})

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ShopSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer, status=400)


@csrf_exempt
def menu(request, shop):
    if request.method == 'GET':
        menu = Menu.objects.filter(shop=shop)
        # serializer = MenuSerializer(menu, many=True)
        # return JsonResponse(serializer.data, safe=False)
        return render(request, 'order/menu_list.html', {'menu_list': menu, 'shop': shop})

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MenuSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer, status=400)


@csrf_exempt
def order(request):
    if request.method == 'POST':
        address = request.POST['address']
        shop = request.POST['shop']
        food_list = request.POST.getlist('menu')
        order_date = timezone.now()
        shop_item = Shop.objects.get(pk=shop)

        shop_item.order_set.create(address=address, order_date=order_date, shop=int(shop))

        order_item = Order.objects.get(pk=shop_item.order_set.latest('id').id)
        for food in food_list:
            order_item.orderfood_set.create(food_name=food)

        return render(request, 'order/success.html')

    elif request.method == 'GET':
        order_list = Order.objects.all()
        return render(request, 'order/order_list.html', {'order_list': order_list})

djangoProject/user/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from user.models import User
from rest_framework.parsers import JSONParser
from django.http import HttpResponse, JsonResponse
from order.serializers import UserSerializer


@csrf_exempt
def user(request):
    if request.method == 'GET':
        user = User.objects.all()
        return render(request, 'user/user_list.html', {'user_list': user})

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = UserSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=200)
        return JsonResponse(serializer.errors, status=400)


@csrf_exempt
def login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')

    elif request.method == 'POST':
        user_name = request.POST['user_name']
        try:
            user_info = User.objects.get(user_name=user_name)
            request.session['user_type'] = user_info.user_type
            return render(request, 'user/login_result.html', {'isSuccessed': True, 'user_info': user_info})
        except:
            pass
        return render(request, 'user/login_result.html', {'isSuccessed': False})

djangoProject/boss/templates/boss/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

	<table border="1">
		<tr style="text-align: center">
			<td>주문시간</td>
			<td>음식</td>
			<td>배달 예상 시간</td>
			<td>배달 완료 여부</td>
		</tr>
		{% for order in order_list %}
		<tr>
			<td>{{ order.order_date }}</td>
			<td>
				{% for food in order.orderfood_set.all %}
					{{ food.food_name }}
				{% endfor %}
			</td>
			<td>
				{% if order.estimated_time == -1 %}
					<form method="post" action="{% url 'timeinput' %}">
						<input type="number" name="estimated_time">분
						<input type="hidden" name="order_id" value="{{ order.id }}">
						<input type="submit" value="예상시간 입력">
					</form>
				{% else %}
				{{ order.estimated_time }}
				{% endif %}
			</td>
			<td>
				{% if order.deliver_finished == 0 %}
				배송중
				{% else %}
				완료
				{% endif %}
			</td>
		</tr>
		{% endfor %}
	</table>

</body>
</html>

djangoProject/boss/templates/boss/success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
주문에 성공하였습니다.
<br>
주문내역을 보시려면 <a href="{% url 'order_list' shop %}">여기를 클릭하세요</a>
</body>
</html>

djangoProject/delivery/templates/delivery/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

	<table border="1">
		<tr style="text-align: center">
			<td>주문시간</td>
			<td>음식</td>
			<td>배달 예상 시간</td>
			<td>배달 완료 여부</td>
		</tr>
		{% for order in order_list %}
		<tr>
			<td>{{ order.order_date }}</td>
			<td>
				{% for food in order.orderfood_set.all %}
					{{ food.food_name }}
				{% endfor %}
			</td>
			<td>
				{% if order.estimated_time == -1 %}
				미정
				{% else %}
				{{ order.estimated_time }}분
				{% endif %}
			</td>
			<td>
				{% if order.deliver_finished == 0 %}
				<form method="post" action="{% url 'delivery:order_list' %}">
                    <input type='hidden' name="order_id" value="{{order.id}}">
                    <input type="submit" value="배송완료 버튼">
                </form>
				{% else %}
				완료
				{% endif %}
			</td>
		</tr>
		{% endfor %}
	</table>

</body>
</html>

djangoProject/delivery/templates/delivery/success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
배송이 완료되었습니다.
<br>
다른 주문내역을 보시려면 <a href="{% url 'delivery:order_list' %}">여기를 클릭하세요</a>
</body>
</html>

djangoProject/order/templates/order/menu_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post" action="{% url 'order' %}">
	<ol>
		<h4> 주문하실 음식을 골라주세요</h4>
		{% for menu in menu_list %}
			<li>
			<input type="checkbox" id="menu{{ forloop.counter }}" name="menu" value="{{ menu.food_name }}"
		    <lable for="menu{{ forloop.counter }}">{{ menu.food_name }}</lable>
			</li>
		{% endfor %}
	</ol>
	<ol>
		<h4> 주소를 입력해주세요</h4>
		<input type="text" name="address" required>
	</ol>
<input type='hidden' name='shop' value="{{ shop }}">
	<input type="submit" value="주문완료하기">
</form>

</body>
</html>

djangoProject/order/templates/order/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

	<table border="1">
		<tr style="text-align: center">
			<td>주문시간</td>
			<td>음식</td>
			<td>배달 예상 시간</td>
			<td>배달 완료 여부</td>
		</tr>
		{% for order in order_list %}
		<tr>
			<td>{{ order.order_date }}</td>
			<td>
				{% for food in order.orderfood_set.all %}
					{{ food.food_name }}
				{% endfor %}
			</td>
			<td>
				{% if order.estimated_time == -1 %}
				미정
				{% else %}
				{{ order.estimated_time }}
				{% endif %}
			</td>
			<td>
				{% if order.deliver_finished == 0 %}
				배송중
				{% else %}
				완료
				{% endif %}
			</td>
		</tr>
		{% endfor %}
	</table>

</body>
</html>

djangoProject/order/templates/order/shoplist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for shop in shop_list %}
	<h5><a href="{%  url 'menus'  shop.id %}">{{ shop.shop_name }}</a></h5>
    <h5>{{ shop.shop_address }}</h5>
{% endfor %}
</body>
</html>

djangoProject/order/templates/order/success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
주문에 성공하였습니다.
<br>
주문내역을 보시려면 <a href="{% url 'order' %}">여기를 클릭하세요</a>
</body>
</html>

djangoProject/user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

	<form method="post" action="{% url 'login' %}">
		이름 : <input type="text" name="user_name">
		<input type="submit" value="로그인">
	</form>

</body>
</html>

djangoProject/user/templates/user/login_result.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

	{% if isSuccessed == True %}
		{{ user_info.user_name }}님 로그인에 성공하였습니다.<br>
		회원구분은
		{% if user_info.user_type == 0 %}
			일반사용자 입니다.
		{% endif %}
		{% if user_info.user_type == 1 %}
			사장님 입니다.
		{% endif %}
		{% if user_info.user_type == 2 %}
			배달라이더 입니다.
		{% endif %}
	{% endif %}
	{%  if isSuccessed == False %}
		로그인에 실패하였습니다.
	{% endif %}

</body>
</html>

djangoProject/user/templates/user/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

	{% for user in user_list %}
		<h5>{{ user.user_name }}  :  {{ user.user_type }}</h5>
	{% endfor %}

</body>
</html>